### ISSUE TITLE
prefix in the settings.toml

### ISSUE THREAD

**Issue by 23tom2323** [mrmay-dev/owntags#6]
I don't yet understand what the prefix information in the settings.toml should look like.

```
owntags/
└── application/
    └── keys/
        ├── prefix-1.keyfile	 # Car1
        ├── prefix-2.keyfile	 # Car2
	├── prefix-2.keyfile	 # Unicorn
	└── prefix-2.keyfile 	 # Dragon
```

@settings.toml

```
[tag_options.prefix prefix-1]
[tag_options.prefix prefix-2]
[tag_options.prefix prefix-3]
[tag_options.prefix prefix-4]


tag_name = "prefix-1" # Car1
tag_name = "prefix-2" # Car2
tag_name = "prefix-3" # Unicorn
tag_name = "prefix-4" # Dragon
```

or should it look like this?

```
owntags/
└── application/
    └── keys/
        ├── car1.keyfile	 
        ├── car2.keyfile	 
	├── unicorn.keyfile	 
	└── dragon.keyfile 	
``` 

@settings.toml

```
[tag_options.prefix]
tag_name = "car1"  
location = true 
waypoint = false  
timestamp = 1000000001  
radius = false  

[tag_options.prefix]
tag_name = "car2"  
location = true 
waypoint = false  
timestamp = 1000000001  
radius = false  

[tag_options.prefix]
tag_name = "unicorn"  
location = true 
waypoint = false  
timestamp = 1000000001  
radius = false  

[tag_options.prefix]
tag_name = "dragon"  
location = true 
waypoint = false  
timestamp = 1000000001  
radius = false  
```

**Comment by Systm21** [comment]
Do you already have prefix files with stored keys? Maybe its a little bit clearer for you, when you have data that you can work with. 

Simplified it should something like this (can test it in the afternoon):

```

[tag_options.car1]
tag_name = "car1"  
location = true 
waypoint = false  
timestamp = 1000000001  
radius = false  

[tag_options.car2]
tag_name = "car2"  
location = true 
waypoint = false  
timestamp = 1000000001  
radius = false  

[tag_options.unicorn]
tag_name = "unicorn"  
location = true 
waypoint = false  
timestamp = 1000000001  
radius = false  

[tag_options.dragon]
tag_name = "dragon"  
location = true 
waypoint = false  
timestamp = 1000000001  
radius = false  

```
@mrmay-dev 
Can i rename the prefixes in the Keyfile? Does it also work? 

MUST be
tag_options.dragon
and
tag_name = dragon 
Identically?
...or can i rename it with tag_name?

**Comment by mrmay-dev** [comment]
@Systm21 , you are right that the prefix name (`[tag_options.dragon]`) MUST match the (`tag_name = "dragon"`).  I think it's redundant and want to work the code so it pulls the prefix from the toml block header.

Yes, changing the prefixes on the keyfile works so long as the name is changed in the `settings.toml`. I named mine for Minecraft items. LOL

Also, check out the timestamps. Each key must be unique.

My keyfiles are:

- `alex.keys`
- `steve.keys`
- `sheep.keys`

and the corresponding TOML blocks read:

```toml
[tag_options.alex]
tag_name = "alex"  
location = true 
waypoint = false  
timestamp = 1000000001  
radius = false  

[tag_options.steve]
tag_name = "steve"  
location = true 
waypoint = false  
timestamp = 1000000002 
radius = false 

[tag_options.sheep]
tag_name = "sheep"  
location = true 
waypoint = false  
timestamp = 1000000003 
radius = false 
```

That's what OwnTracks uses to track waypoints. If the timestamps are the same, OwnTracks thinks it's the same waypoint.
